import { Check, FileUp, Plus, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { documentApi, profileApi } from '../services/api';

const blankProfile = { full_name: '', email: '', phone: '', address: '', location: '', headline: '', skills: [], experience: '', education: '' };

export default function Profile() {
  const [profile, setProfile] = useState(blankProfile);
  const [skill, setSkill] = useState('');
  const [status, setStatus] = useState('');
  const [upload, setUpload] = useState('');

  useEffect(() => { profileApi.get().then(value => setProfile({ ...blankProfile, ...value })).catch(() => setStatus('Start the API to load your profile.')); }, []);
  const update = (key, value) => setProfile(current => ({ ...current, [key]: value }));
  const save = async () => { try { setProfile(await profileApi.save(profile)); setStatus('Profile saved. Future drafts will use this context.'); } catch { setStatus('Could not save profile. Is the API running?'); } };
  const addSkill = () => { const value = skill.trim(); if (value && !profile.skills.includes(value)) update('skills', [...profile.skills, value]); setSkill(''); };
  const uploadFile = async event => { const file = event.target.files?.[0]; if (!file) return; try { const result = await documentApi.upload(file); setUpload(`${result.filename} saved and indexed for answer context.`); } catch { setUpload('Upload failed. Use a readable PDF, DOCX, or TXT file under 8 MB.'); } };
  const field = (label, key, placeholder, large = false) => <label className="block"><span className="mb-1.5 block text-xs font-semibold text-[#52665a]">{label}</span>{large ? <textarea value={profile[key]} onChange={event => update(key, event.target.value)} placeholder={placeholder} rows="4" className="w-full rounded-lg border border-[#dce5dc] px-3 py-2.5 text-sm outline-none ring-[#75b992] focus:ring-2"/> : <input value={profile[key]} onChange={event => update(key, event.target.value)} placeholder={placeholder} className="h-10 w-full rounded-lg border border-[#dce5dc] px-3 text-sm outline-none ring-[#75b992] focus:ring-2"/>}</label>;

  return <div className="mx-auto max-w-4xl px-9 py-10">
    <div className="mb-8"><p className="text-xs font-bold uppercase tracking-widest text-[#438b64]">Your context</p><h2 className="mt-2 text-3xl font-bold tracking-[-1.2px]">Build your application profile</h2><p className="mt-2 text-sm text-[#718177]">Saved profile details and uploaded document text are used to create grounded drafts.</p></div>
    <div className="grid gap-6 lg:grid-cols-[1fr_300px]"><section className="space-y-5 rounded-2xl border border-[#e0e7df] bg-white p-6"><h3 className="font-bold">Personal information</h3><div className="grid gap-4 sm:grid-cols-2">{field('Full name', 'full_name', 'Your name')}{field('Email address', 'email', 'you@example.com')}{field('Phone number', 'phone', '+91 ...')}{field('Location', 'location', 'City, Country')}</div>{field('Street address', 'address', 'House / street / city / postal code')}{field('Professional headline', 'headline', 'A concise, professional introduction')}{field('Experience summary', 'experience', 'Describe your relevant work and impact.', true)}{field('Education', 'education', 'Degree, school, year')}<div><span className="mb-1.5 block text-xs font-semibold text-[#52665a]">Skills</span><div className="mb-2 flex flex-wrap gap-2">{profile.skills.map(item => <span key={item} className="inline-flex items-center gap-1 rounded-full bg-[#e9f5ed] px-2.5 py-1 text-xs font-medium text-[#357f58]">{item}<button onClick={() => update('skills', profile.skills.filter(current => current !== item))}><X size={12}/></button></span>)}</div><div className="flex gap-2"><input value={skill} onChange={event => setSkill(event.target.value)} onKeyDown={event => event.key === 'Enter' && (event.preventDefault(), addSkill())} placeholder="Add a skill" className="h-9 flex-1 rounded-lg border border-[#dce5dc] px-3 text-xs outline-none"/><button onClick={addSkill} className="grid size-9 place-items-center rounded-lg bg-[#eef5ef] text-[#367e58]"><Plus size={16}/></button></div></div><div className="flex items-center gap-4 border-t border-[#edf0eb] pt-5"><button onClick={save} className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#3d9b69] px-4 text-sm font-bold text-white"><Check size={16}/> Save profile</button>{status && <span className="text-xs text-[#55816a]">{status}</span>}</div></section><aside className="h-fit rounded-2xl border border-[#e0e7df] bg-white p-5"><h3 className="font-bold">Source documents</h3><p className="mt-2 text-xs leading-5 text-[#718177]">Upload a résumé, portfolio, or work sample. Its extracted text is retained and searched for answer drafts.</p><label className="mt-5 flex cursor-pointer flex-col items-center rounded-xl border border-dashed border-[#b9d5c2] bg-[#f4faf5] px-4 py-7 text-center"><FileUp size={22} className="text-[#3e9768]"/><span className="mt-2 text-xs font-bold text-[#3e815b]">Upload document</span><span className="mt-1 text-[10px] text-[#789085]">PDF, DOCX, or TXT · up to 8 MB</span><input className="hidden" type="file" accept=".pdf,.docx,.txt" onChange={uploadFile}/></label>{upload && <p className="mt-3 text-xs text-[#4e8466]">{upload}</p>}</aside></div>
  </div>;
}
